### ISSUE TITLE
Blog template

### ISSUE THREAD

**Issue by cfjedimaster** [philhawksworth/11up#2]
That's it - the entire issue - let's add a simple blog template. (I'm volunteering for this, but wanted to raise the issue to ensure it made sense with what you have in mind.)

**Comment by philhawksworth** [comment]
Good idea, and thanks, @cfjedimaster! 

I'm going to be give some thought to what requirements each template must satisfy in order to find a good home here. Initially, I need to ensure that each one has some consistency with the dev and build commands and workflow (because I'm trying to grow familiarity with conventions across all of my own projects, let alone everyone else's . ☺️  )

The official Base Blog template fits and it is maintained, so I'll include that for now and close this issue. But do feel free to open a new issue and share a link to another project repo if you think that would be a good candidate too. Templates are pulled in directly for their own repos, so adding should be simple when a good fit is assured.

Over time, I'll codify the requirements for any template submissions, but it's early days on this little utility.
